# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ANKIT TEWARI
tagline:          'website'
description:      'Find me online <a href="http://twitter.com/acmankit">@twitter</a>, <a href="http://facebook.com/ankit.tewari">@facebook</a>, <a href="http://simplystatistics.org">Simply Statistics</a>, and <a href="https://github.com/ankitbit">Github</a>.'
url:              http://ankitbit.github.io

author:
  name:           'Ankit Tewari'
  url:            https://twitter.com/acmankit

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ankitbit/ankitbit.github.io
