# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ''
tagline:          'Ankit Tewari'
description:      'Find me online <a href="http://twitter.com/acmankit">@acmankit</a>, <a href="http://twitter.com/simplystats">@simplystats</a>, and <a href="https://github.com/ankitbit">Github</a>.'
url:              http://ankitbit.github.io

author:
  name:           'Ankit Tewari'
  url:            https://twitter.com/ankitbit

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ankitbit/ankitbit.github.io
